### ISSUE TITLE
noir js library do not work with modern tool like vitejs.dev

### ISSUE THREAD

**Issue by wighawag** [noir-lang/noir#1075]
### Aim

I would like to keep using vitejs.dev for my frontend

### Expected behavior

And I expect it to work

### Bug

There seems to be multiple issue.
One of them is that it cannot find the wasm file by itself
I got around the issue by moving the file in my static asset folder and load it by passing the url as argument

But then I encountered other issue about TextEncoder not being defined inside aztec_backend.js, then after using globalThis.TextEncoder I get error about __dirname

It seems aztec_backe and lib depending on it relies on node js feature or require statement

It also make use of Buffer which ideally it should not

### To reproduce

(see repo : https://github.com/bug-reproduction/vite-noir)

1. execute the following

```
git clone git@github.com:bug-reproduction/vite-noir.git
cd vite-noir
pnpm i
pnpm dev
```

2. launch a browser to load the page
3. open the console
4. click the button 
5. see the errors

### Installation method

Binary

### Nargo version

nargo 0.3.2 (git version hash: 91bd47190402f0fe567dbfb6fcfa17b97c129905, is dirty: false)

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by Globallager** [comment]
Thanks for filing the Issue nonetheless! We'll link to this when we have a fix.

**Comment by kevaundray** [comment]
@Savio-Sou or @signorecello what is the status of this issue?

**Comment by Savio-Sou** [comment]
The plan is for the core team to deliver the browser packages with Next.js compatibility, and lean more heavily on the community for support with other frontend frameworks (I believe a dev is working on Vite compatibility, @signorecello might know more).

Given how drastically the browser packages workflow would be changing versus when this issue was created (e.g. `aztec_backend.js` would be deprecated), I'd recommend:
1. Reconfirming the issues reported here when the new workflow is released
2. Recreate appropriate issues
3. Close this as stale

**Comment by kevaundray** [comment]
Closing this and opened up another general issue about supporting frontend frameworks: https://github.com/noir-lang/noir/issues/2007
