### ISSUE TITLE
Expensive dynamic array access

### ISSUE THREAD

**Issue by ax0** [noir-lang/noir#1334]
### Aim

Determine the circuit size generated by the following code:
```rust
fn main(input: [u8; 532], i: Field)
{
    let _x = input[i];
}
```

### Expected behavior

Not too many constraints.

### Bug

Running `nargo gates` yields the following output:
```
Total ACIR opcodes generated for language PLONKCSat { width: 3 }: 460279
Backend circuit size: 460230
```

### To reproduce

1. Populate `main.nr` with the above code.
2. Run `nargo gates`.

### Installation method

Compiled from source

### Nargo version

nargo 0.5.1 (git version hash: 260d87d1ef86069a1fcf0f9b4969589273e381d1, is dirty: false)

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by guipublic** [comment]
There are 2 issues here, but none of them is a bug.

The main one is that using sorting networks with Plonk is not efficient because (again) the width reduction causes the gate count to blow-up. The solution is to simply switch to UP ram/rom tables. The code for this is done, but requires cascading updates from BB up to noir. And this is currently blocked because the BB PR is failing one test. I don't understand what would cause the CI to fail on only one platform.

The second issue is because using sorting network for just one read is not worth it (and to some extend this will be true also with UP ram). The solution is to optimise out arrays with low number of access. This is feature to add on top of the dynamic arrays, it is not an issue with the current implementation.

**Comment by kevaundray** [comment]
@guipublic we currently don't have code which checks if using dynamic array is worth it for the old or new code. Can you create an issue linking to this one with that feature request?

**Comment by kevaundray** [comment]
> 

If this is for the experimental-ssa code, then please close this issue
