### ISSUE TITLE
Brillig functions will loop infinitely on cfg flattening pass

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1613]
### Aim

See this PR comment https://github.com/noir-lang/noir/pull/1610/files#r1223615701

### Expected Behavior

.

### Bug

.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
I think to fix these bugs more generally we need to separate the SSA and Brillig IRs, as in we should not generate SSA for Brillig functions, or should at least throw it away after we've used it to create the Brillig.

The `function.runtime()` method should be removed and we can replace it with a new Value kind like we do for intrinsics:
```rs
enum Value {
    ...
    Function(FunctionId),
    Intrinsic(Intrinsic),
    Brillig(Brillig),
}
```
Then once we generate Brillig from a `Call { function, args }`, where `function` refers to a `Value::Function`, we can use `DataFlowGraph::set_value(function, Value::Brillig(brillig_code))` to discard the previous function value and replace it with the brillig code. Ideally we'd remove it from the list of functions in the `Ssa` struct as well. The hard part of doing this is that we'd have to go through each existing function to do the `set_value` replacement since they all have different DataFlowGraphs internally.

**Comment by kevaundray** [comment]
@jfecher I think the above comment should have its own issue, a proposal would also include  things like constrained calling unconstrained and vice-versa.

Closing this issue for now and it can be replaced with the new one
