### ISSUE TITLE
Allow globals to reference other globals

### ISSUE THREAD

**Issue by sirasistant** [noir-lang/noir#1734]
### Problem

When writing modular code It sometimes happens that we have globals that depend on other globals, such as

```rust
global MAX_ARGS = 8;

global PUBLIC_INPUTS_LEN = MAX_ARGS + 3;
```

However, this is not currently supported by the language, so we need to have explanatory comments and do searches to find usage which is quite error prone:

```rust
global MAX_ARGS = 8;

// MAX_ARGS + OTHER_STUFF
global PUBLIC_INPUTS_LEN = 11;
```

### Happy Case

Globals could be the result of compile time arithmetic expressions. Even better if they can be the result of function calls that return comptime values, but just being able to define them with arithmetic expressions would be very helpful.

### Would you like to submit a PR for this Issue?

No

**Comment by sirasistant** [comment]
Relates to https://github.com/noir-lang/noir/issues/461

**Comment by jfecher** [comment]
> Relates to https://github.com/noir-lang/noir/issues/461

#461 is unrelated actually. It was a potential evaluation scheme for comptime expressions but does not deal with what kinds of expressions we allow for globals.

To provide more of a background on the reasoning why globals aren't allowed to reference other globals currently, if we allowed
```rs
global MAX_ARGS = 8;

global PUBLIC_INPUTS_LEN = MAX_ARGS + 3;
```
Then it follows that the following would also be possible:
```rs
global MAX_ARGS = PUBLIC_INPUTS_LEN + 8;

global PUBLIC_INPUTS_LEN = MAX_ARGS + 3;
```
Since globals, like functions are able to be referenced at a global scope before they're defined. We'd have to find a way to prevent circular dependencies like this in general with a good error message. Solving this is not as simple as "allow globals to reference other globals defined beforehand in the same file" since we must also worry about imports from other files and, if we allow function calls as well, functions that capture globals before they're defined such as:
```rs
global BAD = init_bad();

fn init_bad() -> Field {
    BAD + 1
}
```
You can see how this function would clearly be erroneous but this can occur in more subtle ways accidentally as well. E.g. via indirectly called functions.

**Comment by kevaundray** [comment]
This was my mistake for mis-remembering, I mis-remembered and thought we were using that as a potential to evaluate global constants
