### ISSUE TITLE
ACIR gen extremely slow for `eddsa`

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1750]
### Aim

Compile time should be comparable to old SSA solution.

### Expected Behavior

^

### Bug

Compiling the example `eddsa` with `--experimental-ssa` takes approximately 13 minutes on my 2.3 GHz 8-Core Intel Core i9 MacBook Pro. By contrast the old implementation only takes 1 minute to compile. The time is spent predominantly in ACIR gen.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by joss-aztec** [comment]
I'm timing this again and it's taking a lot longer than 13 minutes this run... already passed 30mins

**Comment by joss-aztec** [comment]
Over an hour has passed - killing it.

**Comment by jfecher** [comment]
The `eddsa` test is now hanging during calling `find_branch_ends` in the flattening pass.

**Comment by jfecher** [comment]
Because acir-gen iterates instruction by instruction it is fairly easy to get a progress bar of how far and how fast it is going. My initial impressions are:

1. It is much too slow for larger programs, of course as identified by this issue, and
2. It seems to get slower with each additional instruction pushed. At instruction 6000/67000 it was taking ~3.5-4s to process 100 instructions. At instruction 20000 / 67000 it was taking closer to 7s.

**Comment by kevaundray** [comment]
Re-opening this issue as eddsa takes a long time still cc @Ethan-000 for visibility
