### ISSUE TITLE
Make the incremental variable i in "for i in 0..420" mutable

### ISSUE THREAD

**Issue by harshnambiar** [noir-lang/noir#1819]
### Problem

Currently, the loop HAS to run that many times irrespective of the purpose of the loop being fulfilled or not. For example, finding a particular value n in an array or length 100 (say arr[1] == n, but still the loop will not terminate). This leads to a lot of loss of efficiency and computing, and can be avoided if the variable i were mutable.

### Happy Case

Suppose in the above example, i were mutable. Then as soon as an element equal to n was discovered,

for i in 0..420 {
if arr[i] == n {
i = 420;
}
};
This would in a way, be the equivalent of a break statement, without having to bother about creating a new keyword for Noir. This might help solve said problem.

### Alternatives Considered

Alternatively, if a for loop can be constructed to accommodate 2 conditions, where the first is i, an iterator, and the second is a bool type that can denote if the purpose of the loop is already fulfilled, that would work too.

for i in 0..420 & !purp{
if arr[i] == n {
purp = true;
}
};

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
Sounds like this is a work around for the lack of a `break` statement. Would you rather `break` statements were added instead?

My main worry with a mutable induction variable is that we must guarantee loops terminate so we can always unroll them in the compiler. If users can mutate `i` then there is less guarantee onto what `i` depends on. Even if it should be compile-time known, it may be that different optimization passes are needed and their ordering may cause loop unrolling to fail. For example, we currently handle mutable variables in a separate after loop unrolling so if that is not changed then loop unrolling with a mutable variable will fail. Similarly `if` expressions are flattened after loop unrolling, so any mutation within an `if` would also not be able to be tracked until then. From a compiler internals perspective (and I think a user-facing one as well), I think opting for `break` instead is cleaner.

**Comment by kevaundray** [comment]
Since Noir compiles down to a single circuit per program, I don't think you would gain anything in terms of efficiency (smaller circuit size) -- It would make it so that execution of the circuit was more efficient however, since the prover could zero out portions of the circuit.

I think if we were to add something like this in, we would add in a `break/continue` statement, because the code you wrote above with mutable `i` is a bit of a footgun in Rust. For example, if you compile the following in a Rust playground:

```rust
fn main() {
    for mut i in 0..10 {
        i = 10;
        println!("{}",i);
    }
}
```

one may expectas in your example, that this loop runs once. However, in Rust this will run ten times and print the number `10` ten times.
