### ISSUE TITLE
Reconsider type inference for globals

### ISSUE THREAD

**Issue by ludamad** [noir-lang/noir#1862]
### Aim

It's quite unintuitive (sorry if Bug is a strong word) ATM when you have a constant

`global MAX_PLAYERS = 2;`

And then multiply it with a `Field`, it is suddenly a `Field` everywhere in your program. Top-level symbols should probably be have explicit types, like Rust top-level consts

### Expected Behavior

I expected a for i in 0..MAX_PLAYERS loop to work even though MAX_PLAYERS is used in field math
If MAX_PLAYERS wont be polymorphic, it should probably require an explicit type

### Bug

-

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
```rs

global MAX_PLAYERS = 2;

fn main(some_field_value: Field) {
    let _x = MAX_PLAYERS * some_field_value;

    for i in 0 .. MAX_PLAYERS {
        assert(i as u32 < 10);
    }
}
```
Works for me, perhaps your code has another issue?

As for the original question, I personally don't find the behavior too confusing but you can always optionally specify a type annotation if desired. We don't generalize the types of globals but we could in theory since they are compiled by substituting each use of them with their definition.

**Comment by ludamad** [comment]
Closing as I can't reproduce now. Will reopen if I can.
