### ISSUE TITLE
Unsigned integer division doesn't work with `--experimental-ssa`

### ISSUE THREAD

**Issue by shuklaayush** [noir-lang/noir#1923]
### Aim

```rust
use dep::std::println;

#[test]
fn test_div() {
    let a: u16 = 5;
    let b: u16 = 2;

    let c = a / b;

    // 0x183227397098d014dc2822db40c0ac2e9419f4243cdcb848a1f0fac9f8000003
    println(c);
    // This fails
    assert(c == 2);
}
```

### Expected Behavior

The test should pass

### Bug

Dividing unsigned ints with `--experimental-ssa` seems to calculate multiplication with the field inverse instead of standard integer division

### To Reproduce

1. Copy the above code
2. Run the test
```bash
nargo test --show-output --experimental-ssa
```

### Installation Method

Compiled from source

### Nargo Version

nargo 0.8.0 (git version hash: 4969da7b4dea9f0377eee7521be21415a5ebf55e, is dirty: false)

### Would you like to submit a PR for this Issue?

Maybe

**Comment by kevaundray** [comment]
Thanks for opening this issue and bring it up on the call!

The bug is in this function: https://github.com/noir-lang/noir/blob/4969da7b4dea9f0377eee7521be21415a5ebf55e/crates/noirc_evaluator/src/ssa_refactor/ir/instruction.rs#L771

When we have instructions with constant values, they get simplified on the fly. The problem is that our simplification pass is not taking into consideration the type. See division where it is doing `lhs / rhs` where these are FieldElements.

This method should be modified to check if we want to do field arithmetic or integer arithmetic and evaluate the constant expression accordingly.

Note: that this will only fail for constants. Non-constants won't be simplified and we do the division via acir_gen.
