### ISSUE TITLE
Visibility declarations inside structs

### ISSUE THREAD

**Issue by n4ru** [noir-lang/noir#2135]
### Problem

Creating commitments to data that contains mixed public/private fields cannot be cleanly done with structs at the moment because you cannot declare it inside of the struct. Instead, one needs to have the public inputs handled outside of the struct. Would be nice to have some syntaxic sugar to handle them inside of structs.

### Happy Case

Pretty self explanatory, I want to be able to add `pub` inside of structs.

```
struct Animal {
    identifier: pub Field,
    hands: Field,
    legs: Field,
    eyes: u8,
}
```

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
This was intentional because you may then be able to do something like:

```
fn main(animal : pub Animal) {}
```

Which would be ambiguous because the struct declares identifier to be public, but then the parameter declares the whole struct to be public.


We _could_ say that you cannot add `pub` infront of a user defined structs, only primitive types. The only downside here is that if you have a large struct which needs all of its fields to be public, it can be repetetive.

A weak argument which I hope can spur discussion -- is that having `pub` allowed outside of the main functions parameters may cause confusion when we introduce visibility declarators, ie we may end up with something like:

```
pub struct Animal {
    identifier: pub Field,
    hands: Field,
    legs: Field,
    eyes: u8,
}
```
 
where `pub struct` tells us that this field can be accessed anywhere it is imported and pub Field tells us that it is a "public witness" in the proof system. 

The counter for this is that we should likely create a new keyword for visibility, do you have any insights on what would be a better keyword or whether you find the reuse of the word pub to be problematic?

**Comment by jfecher** [comment]
> Creating commitments to data that contains mixed public/private fields cannot be cleanly done with structs at the moment because you cannot declare it inside of the struct. Instead, one needs to have the public inputs handled outside of the struct. Would be nice to have some syntaxic sugar to handle them inside of structs.

You should still be able to store public inputs within structs and they'll remain public as long as they're unchanged. E.g:
```
fn main(x: pub Field) {
    let a = Foo { x };
    let b = (x, x);
    ...
    let c = Foo { x: x + 1 };
}
```
Both `a` and `b` contain the public `x` but the `Foo::x` within `c` will be a private witness since it is a new value derived from the original x.

**Comment by TomAFrench** [comment]
I'm going to close this issue as specifying this visibility on the struct definition causes issues in situations such as
- the struct is defined in a library and so the developer cannot modify the definition.
- the struct is used in multiple arguments to `main` which require different visibilities.

In this scenario I'd recommend implementing a new struct which contains only the public fields which implements `From` for the original struct. This can then be easily returned from the circuit to make a subset of the fields public. There'll be some boilerplate for large structs but I think this can be avoided in future using the metaprogramming proposal.

```rust 
struct RedactedStruct {
   ...
}

impl From<Struct> for RedactedStruct {
   ....
}
fn main(x: Struct) -> pub RedactedStruct {
    x.into()
}
```

As a bonus, this guarantees that we can generate TS types for these structs so they can be easily manipulated in javascript.
