### ISSUE TITLE
Question regarding defunctionalization

### ISSUE THREAD

**Issue by Ethan-000** [noir-lang/noir#2192]
### Problem

```rust
use dep::std;
fn main() {
    let a = 1;
    let c = foo(a, bar, baz);
    assert(c==1);
}

fn foo(a: Field, f: fn(Field) -> Field, g: fn(Field) -> Field) -> Field {
    g(f(a))
}

fn bar(b: Field) -> Field {
    b
}

fn baz(c: Field) -> Field {
    c
}
```

This code generates 

```rust
acir fn main f0 {
  b0():
    v4 = call f1(Field 1, Field 2, Field 3)
    v5 = eq v4, Field 1
    constrain v5
    return 
}
acir fn foo f1 {
  b0(v0: Field, v1: Field, v2: Field):
    v3 = call f4(v1, v0)
    v4 = call f4(v2, v3)
    return v4
}
acir fn bar f2 {
  b0(v0: Field):
    return v0
}
acir fn baz f3 {
  b0(v0: Field):
    return v0
}
acir fn apply f4 {
  b0(v0: Field, v1: Field):
    v3 = eq v0, Field 2
    jmpif v3 then: b2, else: b1
  b2():
    v6 = call f2(v1)
    jmp b3(v6)
  b3(v4: Field):
    return v4
  b1():
    v8 = eq v0, Field 3
    constrain v8
    v11 = call f3(v1)
    jmp b4(v11)
  b4(v9: Field):
    jmp b3(v9)
}
```

q1: should `b2()` also have a constrain like `b1()` or is it implicit with `jmpif`
q2: currently every function that is dispatched generate a new return block that points to the exisiting return block. is it better to just call the existing return block if there is one

### Happy Case

. 

### Would you like to submit a PR for this Issue?

Maybe

**Comment by sirasistant** [comment]
> q1: should b2() also have a constrain like b1() or is it implicit with jmpif

The constrain in b1 is a sanity check. If you have an apply function like f4 that can dispatch to either bar or baz, with ids 2 and 3 respectively, you first compare the target id with 2 and then, if the target id is not 2, you compare it with the last possibility, 3, and assert that it has to be equal to 3. We only do this in the last possibility as a sanity check that the compiler has not translated a function to a value that wasn't considered in the corresponding apply function. (for example, if the compiler didn't consider a function with id 9 when creating the apply function, this constrain will fail instead of silently dispatching to `baz`

> q2: currently every function that is dispatched generate a new return block that points to the exisiting return block. is it better to just call the existing return block if there is one

Yes, this is because in our SSA representation blocks can only have up to two predecessors, so we do this schema for returning:
- Real return <= first function match
- Real return <= 1st nested return
  - 1st nested return <= second function match
  - 1st nested return <= 2nd nested return
    - 2nd nested return <= third function match
    ....
    
We should be able to skip this for the last match because we know that we don't need to create a nested return for any subsequent matches, It should reduce by 1 the number of jmps in all apply fns!

**Comment by jfecher** [comment]
> Yes, this is because in our SSA representation blocks can only have up to two predecessors, so we do this schema for returning:
>    - Real return <= first function match
>   -  Real return <= 1st nested return
>        1st nested return <= second function match
>        1st nested return <= 2nd nested return
>            2nd nested return <= third function match
>            ....
>
> We should be able to skip this for the last match because we know that we don't need to create a nested return for any subsequent matches, It should reduce by 1 the number of jmps in all apply fns!

To expand on this, that nested structure is only because our SSA's only way of jumping to potentially several different blocks is `jmpif` which can only jump to the first block if the condition is true, and the second otherwise. For the return block, there is a pattern of only having a single `return` instruction in each ssa function. So we have one return block usually with a block parameter that it returns, and every block that wants to return instead jumps to that block with their desired return value as an argument. In the `apply` function in your example, the return block would be `b3` and we can see both `b2` and `b4` jump to it rather than `return`ing directly.

Having only one return block just makes some optimizations easier.
