### ISSUE TITLE
Panic when attempting to get location for `RuntimeError::UnsupportedIntegerSize` error

### ISSUE THREAD

**Issue by Jurarpereurs** [noir-lang/noir#2193]
### Aim

I'm trying to convert a field variable to an integer so that I can compare two field variables. However, when I try to do this, Noir crashes:

```rust
fn main(x : Field, y : pub Field) {
    assert((x as u253) < (y as u253));
}
```

### Expected Behavior

Noir should not crash when converting `Field` to `u253`.

### Bug

Noir panicked when doing `x as u253`, where `x` is a `Field` variable.

### To Reproduce

Save the following code into `src/main.nr`:

```rust
fn main(x : Field, y : pub Field) {
    assert((x as u253) < (y as u253));
}
```

Save the following as input into `Prover.toml`:

```toml
x = "1"
y = "2"
```

Run the following command:

```bash
nargo prove
```

You would see the following error message:

```bash
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: crates/noirc_evaluator/src/errors.rs:74

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

### Installation Method

Binary

### Nargo Version

nargo 0.9.0 (git version hash: effb02afc78f379d023719a0d869f42e7109b05f, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
Hey @Jurarpereurs, thanks for reporting this. Looks like the issue is that no location is being attached to the `<` instruction so when this errors then it's unable to show the location of the error which causes the panic.

Once thing I should flag up is that you won't be able to use `u253` like this even once this issue is fixed as integer operations could cause the field to overflow. We'll instead just show an error message rather than panic:

https://github.com/noir-lang/noir/blob/effb02afc78f379d023719a0d869f42e7109b05f/crates/noirc_evaluator/src/ssa/acir_gen/mod.rs#L796-L806
