### ISSUE TITLE
Run workspace/contract compilation in parallel

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2205]
### Problem

We're currently compiling each package in a workspace sequentially (similarly for contract functions). This doesn't take advantage of multiple cores which would speed up compilation times.

### Happy Case

We should compile each package/contract function on a separate thread (up to a maximum depending on the user's system. WASM is also restricted for this.)

Care needs to be taken so that errors, etc. are printed correctly rather than being interwoven.

### Additional Context

This should be delayed until after the rest of the workspace changes being made.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@TomAFrench are you not the best person to take this on?

**Comment by TomAFrench** [comment]
I could take it on but it's a matter of prioritisation. `aztec-packages` would be the main beneficiary of this issue being resolved but they're currently handling this through spinning up multiple instances of `nargo` to compile the contracts individually.

At the same time there's monorepoing work to do, ABI encoding packages to make, etc. which allow us to move faster or are tied to epics which we've committed to. This means I'm unlikely to work on this in the short term.

**Comment by TomAFrench** [comment]
More generally, carrying a lot of assigned issues has drawbacks:
- I'm less able to use the issues which are assigned to me to me in planning my day/week it's turned into another backlog rather than a focused list.
- Having this issue assigned to me gives the impression that it's "mine", which means
  - External contributors are less likely to pick this up.
  - Readers of this issue get the expectation that I am or should be actively working on it.

**Comment by kevaundray** [comment]
> External contributors are less likely to pick this up.
That's a fair point regarding external contributors being less likely to pick it up, I was aiming to have most issues have an owner per-se, so that there were none that fell by the wayside. 

I'll remove owners from issues which are good first issues and then remove owners from issues which I think are good for onboarding external developers and use the "help-wanted" label for those.

> I'm less able to use the issues which are assigned to me to me in planning my day/week 

Ah thats good feedback, I thought that the P-HIGH/MEDIUM categorization would have helped, but checking, I can see that a lot of things assigned to you are P-MEDIUM, so it does turn into a bit of a backlog.
