### ISSUE TITLE
Cannot add a binary package as a dependency

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#2215]
### Aim

Tried to add a package that has `type = "bin"` in its `Nargo.toml` as a dependency

### Expected Behavior

Behavior should match cargo where a package can be used as either a binary or a library based on whether it has a main.rs or a lib.rs.

### Bug

```
Error: Package `my_package` has type `bin` but you cannot depend on binary packages

Location:
    crates/nargo_cli/src/cli/mod.rs:74:5
exit 1
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
I think we should support both `main.nr` and `lib.nr` simultaneously

**Comment by phated** [comment]
As @TomAFrench stated, this is a conscious decision to derivate from cargo. Copying directly from @kevaundray

> For reference, this is allowed in Rust, but on Zulip they said that it was there because they did not support workspaces initially.
So in Rust you can have a `lib.rs` and `main.rs` , what happens here is that you essentially have two crates, the library crate and the binary crate.
The binary crate will call the library crate as if it were an external crate, so if the items are not made public in `lib.rs` they cannot be seen in `main.rs`. I opted out of this because in my head, it was clearer to have two separate projects that showed that actually you have two separate crates
