### ISSUE TITLE
Releases don't contain binaries anymore

### ISSUE THREAD

**Issue by themighty1** [noir-lang/noir#225]
Hi, the latest tags in the Release section only contain source code, no binaries. Did you stop releasing binaries?

**Comment by kevaundray** [comment]
Hi, 

This is a great observation. We are currently working around some limitations of linking the C++ backend, which unfortunately breaks the CI. Before this, we were including the backend as a WASM module, this was slower but compiled due to there being many useful tools such as wasmerio which are capable of loading wasm modules without an issue.

The current goto is to compile from source as we work around this issue. If you are on Linux, the compilation workflow is usually quite straightforward. For Mac (Intel/ARM), it can be quite tedious.

Once the CI workflow is fixed, we will start releasing binaries automatically with tags as we used to.

**Comment by TomAFrench** [comment]
Closing as the issues are fixed and nightly builds being uploaded again :tada:
