### ISSUE TITLE
Expected type [Field], found type [Field; 94]

### ISSUE THREAD

**Issue by kobyhallx** [noir-lang/noir#2367]
### Aim

to use arrays as parameter to main and avoid error such as:

`Cannot have variable sized arrays as a parameter to main`

### Expected Behavior

Compilation resulting in no errors.

### Bug

I'd like to be able specify size with `[Field; 114]`.

This results in error:

`Expected type [Field], found type [Field; 114]`

### To Reproduce

1. Write main function with sized array as input
2. compile with nargo

### Installation Method

Binary

### Nargo Version

nargo 0.10.1 (git version hash: ba8ffd84c19b3516334c126bc2f25c725985baa3, is dirty: false)

### Additional Context

To workaround use

```
fn main(value : [Field; 114]) {
  let value: [Field] = value;
}
```

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
> 
```
fn main(value : [Field; 114]) {
      let value: [Field] = value;
}
```
It looks like in your example you already use an array of length `114` as an input in main without error.

Can you post the full snippet of code you're using? From the error message it looks like you're using an array where a slice was expected. You can use `.as_slice()` to explicitly convert from array to slice.

**Comment by 0xrishabh** [comment]
@jfecher Getting the same error as OP, over this.

<img width="300" alt="image" src="https://github.com/noir-lang/noir/assets/38362547/54eea44e-656c-470c-9307-8ca043321a09">
<img width="1127" alt="image" src="https://github.com/noir-lang/noir/assets/38362547/3dc354ad-b097-4f1d-85d1-20205b1f10b0">

**Comment by jfecher** [comment]
@0xrishabh unfortunately as the error says, you cannot have variable sized arrays as a parameter to your `main` function in Noir. This includes your `y: [u32; N]` and `x: [(...); N]` parameters, both of which do not have a statically known size. This is a limitation of Noir where your inputs must have a known size.

If you want to try to workaround this, the main workaround is to accept arrays of a suitably large size, and pad any smaller arrays with 0 or some other value.

I'm going to close this issue because the original error by @kobyhallx was a user error rather than a compiler one.
