### ISSUE TITLE
Move all forks of dependencies to the noir-lang organisation

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#241]
When we fork a dependency for use in noir, we should add it to noir-lang so that everything is in one place

**Comment by kevaundray** [comment]
@jfecher the only forked dependency that I'm aware of is the chumsky parser -- can you check to see if the newer versions of chumsky do not require us to fork and if we are still required, can you put the fork under the noir-lang organisation?

**Comment by jfecher** [comment]
Although the master branch is being updated, there have yet to be any new versions of chumsky (latest is 0.8.0 from 2022-02-07). The extra parser we need has since been merged to master and we can migrate the next time a version is released. I can work on moving the chumsky fork since I am not sure how long it will take for a new chumsky version to be released.

**Comment by TomAFrench** [comment]
Closing in favour of #853 as it's the only known form we depend on.
