### ISSUE TITLE
The type [u32]  cannot be represented in ACIR

### ISSUE THREAD

**Issue by 0xrishabh** [noir-lang/noir#2535]
### Aim

Given an array, the program tries to get another of length `y`.
```
use dep::std;
use dep::std::collections::vec::Vec;

global DEPTH: Field = 40000;
fn main(x: [u32; DEPTH], y: u32) {
    let mut new_x = Vec::new();
    new_x = clear(x, y);
}

unconstrained fn clear(x: [u32; DEPTH], y: u32) -> Vec<u32> { 
  let mut a = Vec::new();
  for i in 0..y{
    a.push(x[i]);
  }
  a
}
```

### Expected Behavior

Should have run successfully, to populate `new_x` with values 

### Bug

But when running it gives an error:
 _internal error: entered unreachable code: The type [u32]  cannot be represented in ACIR_

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

Yes

**Comment by jfecher** [comment]
Unfortunately, `Vec<T>` cannot be passed between `unconstrained` and non-unconstrained functions because it contains a slice internally. Slices and references are both prohibited to cross this boundary, although for different reasons. For slices it is because we'd need to know their exact length at that point - so you'd need to convert them to an array. For references, it is because any mutations to the reference inside the unconstrained function will not be observed outside.

I'll work on a better user-facing compiler error to explain this.
