### ISSUE TITLE
Multiple `mod foo;` declarations of the same module will duplicate the module

### ISSUE THREAD

**Issue by huangliang-hl** [noir-lang/noir#2658]
### Aim

Embedding one struct as a property of another struct.

### Expected Behavior

It should be able to compile and run successfully, declaring this struct object.

### Bug

```
error: Expected type Tensor<_, 2>, found type Tensor<100, 2>
   ┌─ /mnt/code/convolution/test/linear/src/main.nr:17:36
   │
17 │     let linear_layer = Linear::new(weight1, bias1);
   │                                    -------

error: Expected type Tensor<_, 2>, found type Tensor<10, 2>
   ┌─ /mnt/code/convolution/test/linear/src/main.nr:17:45
   │
17 │     let linear_layer = Linear::new(weight1, bias1);
   │                                             -----

error: Expected type Tensor<_, 2>, found type Tensor<10, 2>
   ┌─ /mnt/code/convolution/test/linear/src/main.nr:21:46
   │
21 │     let linear_output = linear_layer.forward(input);
   │                                              -----

Error: Aborting due to 3 previous errors

Location:
    crates/nargo_cli/src/cli/mod.rs:74:5
```

### To Reproduce

1.git clone https://github.com/storswiftlabs/convolution.git
2.cd convolution/test/linear
3.nargo execute
4.

### Installation Method

None

### Nargo Version

nargo 0.11.1 (git version hash: 9da822f59923a9953894c43afd1ddbeffa871dbf, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
I'm upgrading this from E-LOW to E-MEDIUM. After some investigation, the issue is that the type checker sees the "Tensor" in the parameter and the argument as two separate types. They're assigned different unique type ids, but the internal fields are identical, including their source spans.

**Comment by jfecher** [comment]
Alright, so this issue is because in `conv.nr` you have:
```
mod quantize;
mod tensor;
```
Despite you also declaring `mod tensor;` in `main.nr` and `mod quantize;` elsewhere as well. This is not importing these modules, this is actually creating an identical copy of these modules each time, hence the types within being the same but mutually incompatible.

We should have a better check in the compiler to prevent this, but for now remove the extra `mod` declarations and use `mod foo;` only for declaring submodules in the future. Note that without `mod tensor;` in `conv.nr`, you can still reference tensor's functions with `use crate::tensor;` or just prefixing `crate::tensor::` in front of each function name each time you call them.
