### ISSUE TITLE
Allow recursive datatypes in `Option<T>`

### ISSUE THREAD

**Issue by harshnambiar** [noir-lang/noir#2673]
### Problem

In Noir, currently an Option is a struct with a bool and a varied type field, meanwhile in Rust, it is an enum of a varied type field and None. This kind of implementation will enable types like List to be created.
struct List<T> { first: T, next: Option<List<T>>}  

### Happy Case

If this is to be implemented, it would require the implementation of both enum and None in Noir

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
Unfortunately, Noir's backend works very different to rust's. Rust can represent enums sharing the same memory space and can have `Option<Box<T>>` without actually initializing the `Box<T>`. Since Noir compiles to circuits rather than a normal computer program using memory and CPU instructions, Noir doesn't have this option. Notably, every field of every type must be decomposed into a Field value eventually, and we must know exactly how many of these there will be at compilation time. From this, if we had something like the `List` enum, we would not be able to figure out how many `Fields` it could hold. Is it 0 for the None case? Or is it some `N + 1` for the `Some` case with `N` potential more Lists inside? This is also the reason variable sized arrays aren't accepted as inputs to main.

**Comment by harshnambiar** [comment]
Hey. If somehow the recursive type declarations can be managed without an enum based Option<T>, that's great too and will work. But won't we still need a None?

**Comment by jfecher** [comment]
@harshnambiar I'm not sure what you're suggesting, but the problem isn't `None`. The problem is that recursive types fundamentally have infinite size if everything must be initialized - which it must be in Noir due to Noir's compilation target being a circuit.
