### ISSUE TITLE
Fix failing noi_wasm test in CI

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#3033]
### Aim

Currently Test noir_wasm is failing the CI -- on master the error is:

https://github.com/noir-lang/noir/actions/runs/6436173480/job/17479101660

### Expected Behavior

Tests to pass

### Bug

Backend related error, though its strange for two reasons:

- The backend failure message reason is blank, even though we merged a PR to add this
- The WASM version should not require the backend -- it should get the information needed by the info command from typescript

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
This seems like an intermittent failure in `bb`, rerunning that workflow results in [no backend error](https://github.com/noir-lang/noir/actions/runs/6436173480/job/17519964570). The error here is the one introduced in https://github.com/noir-lang/noir/pull/2989

> The backend failure message reason is blank, even though we merged a PR to add this

It's likely that `bb` is just returning nothing on an error. See https://github.com/noir-lang/noir/issues/2790#issuecomment-1735378959

> The WASM version should not require the backend -- it should get the information needed by the info command from typescript

We use the CLI in order to check that we get the same build outputs based on the same commit.

**Comment by TomAFrench** [comment]
closed  by #3040 and #3039
