### ISSUE TITLE
Compiler panics on unsupported types to `main` rather than issuing a compiler error

### ISSUE THREAD

**Issue by jordan-public** [noir-lang/noir#3062]
### Aim

nargo --version
nargo 0.10.5 (git version hash: 91efe44d17762ea883d9a576d530049ad20f1393, is dirty: false)

git clone git@github.com:Savio-Sou/recursion-demo.git

nargo compile

### Expected Behavior

Success

### Bug

after fixing to:
fn main(
    verification_key : [Field], 
    proof : [Field], 
    public_inputs : [Field], 
    key_hash : Field, 
    input_aggregation_object : [Field; 16],
    proof_b : [Field],

nargo compile
The application panicked (crashed).
Message:  internal error: entered unreachable code: ICE: Params to the program should only contains numbers and arrays
Location: crates/noirc_evaluator/src/ssa/acir_gen/mod.rs:283

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml

### To Reproduce

1. See above
2.
3.
4.

### Installation Method

Binary

### Nargo Version

nargo 0.10.5 (git version hash: 91efe44d17762ea883d9a576d530049ad20f1393, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
Apologies for the bad error message! The error is trying to say that only numbers (field & integer types) and arrays (not slices!) are supported as parameters to `main`. So in your example:

```rs
fn main(
    verification_key : [Field],
    proof : [Field],
    public_inputs : [Field],
    key_hash : Field,
    input_aggregation_object : [Field; 16],
    proof_b : [Field],
)
```
Several parameters are slices instead of arrays which causes this panic. We'll work on making this panic a proper error message but when that is done the code will still be invalid. As a workaround to not supporting slices, you can choose an arbitrary maximum size for each slice, change them to arrays, and fill the rest of the new elements with some padding in the Prover.toml.
