### ISSUE TITLE
Single digit hex literals result in an InvalidIntegerLiteral error

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#3235]
### Aim

Writing `0x4` in a program

### Expected Behavior

The integer `4`

### Bug

```
error: InvalidIntegerLiteral : "0x4" is not a integer
   ┌─ /../short/src/main.nr:35:9
   │
35 │         0x4
   │         ---
   │
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
This error also looks like it was never meant to be shown - we should not display the actual error kind InvalidIntegerLiteral to the user.

**Comment by VictoriaGrasshopper** [comment]
It looks like this error happens not only with single digit hex literals, but with an odd amount of symbols in hex literals.
![image](https://github.com/noir-lang/noir/assets/68955226/e7546ec9-4c2f-4484-9b70-fe815c195e40)

As I understood that the problem lies in this code fragment (probably, [hex::decode()](https://github.com/noir-lang/noir/blob/master/tooling/noirc_abi/src/lib.rs#L395) couldn't parse such values):
https://github.com/noir-lang/noir/blob/master/acvm-repo/acir_field/src/generic_ark.rs#L267

**Comment by sambarnes** [comment]
@jfecher i took a stab at this over coffee this morning^

thanks for the pointer on code loc here @VictoriaGrasshopper :pray: :crown:
