### ISSUE TITLE
Add a `derive` attribute with support for (de)serialize macros on existing complex types

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#3379]
```[tasklist]
### Blocked by
- [ ] https://github.com/noir-lang/noir/issues/2568
```

### Problem

@rahul-kothari brought up that Noir does not currently have a canonical way of (de)serializing all types (including custom structs), hence users have to write their own custom methods to achieve so.

An example of [such custom method in Aztec.nr](https://github.com/AztecProtocol/aztec-packages/blob/26ef8ff78a6ae5a8ebb1f1a35c87f37c33cf1e44/yarn-project/aztec-nr/aztec/src/types/type_serialization/aztec_address_serialization.nr#L14).

### Happy Case

@kevaundray suggested we could add [a `derive` attribute similar to Rust](https://doc.rust-lang.org/beta/reference/attributes/derive.html) with support of [derive macros](https://doc.rust-lang.org/beta/reference/procedural-macros.html#derive-macros).

For this GitHub Issue, we can aim at:
1. Add `#[derive(serialize)]` and `#[derive(deserialize)]`
2. For all complex data types that currently exist natively in Noir (i.e. arrays, tuples, slices, vectors, structs, traits)

P.S. Pardon my lack of knowledge in Rust. If the scope does not make sense, definitely comment below.

Support for e.g. additional derive macros, custom derive macros definable by users can be added later with separate issues.

### Additional Context

@kevaundray noted that his might not necessarily be the best solution for the problem **if** the serialization needs to be duplicated in another language like TypeScript.

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
Assigning `P-HIGH` as @rahul-kothari suggested this is helpful for both Aztec.nr development and most if not all its users.

**Comment by jfecher** [comment]
I think we should wait until after we have traits for this. We'll likely want the `derive` macro to be able to derive certain traits like it can in rust, with Serialize and Deserialize being two of those traits.

**Comment by Savio-Sou** [comment]
Thanks @jfecher, added Traits as a blocker of this Issue.

**Comment by Savio-Sou** [comment]
@kevaundray @jfecher would you anticipate this to be considerably more complex to implement versus https://github.com/noir-lang/noir/issues/2240? (Otherwise seems like this could be a super set of that.)

**Comment by rahul-kothari** [comment]
@jfecher when will Noir start using traits? Aren't they already at least experimental? I remember Kev saying we could use them in sandbox land

**Comment by jfecher** [comment]
@rahul-kothari no official time on them yet since they're still experimental. They're in the compiler already for the most part but you'll receive warnings if you try to use them as there are still some missing features and edge cases. Most notably I'm working now to add support for generics to traits which is important since generics are required for even something as simple as equality on arrays.

You may be fine using them now if you're alright with the warnings and limit yourself to only non-generic types on non-generic traits. ETA for generics is... perhaps roughly 1 months time.

**Comment by jfecher** [comment]
@Savio-Sou I suppose adding a `derive` macro version to derive Serialize/Deserialize would be a bit more complex than writing a built in function to do so. It's just that we know we want a derive macro solution already for traits anyway, so tacking this onto that is essentially little extra work. Compared to the builtin function approach which we may want to remove once we have a trait version of (De)Serialize.

**Comment by jfecher** [comment]
We have `derive` in Noir's stdlib now so it should be possible to define your own deriver function to derive Serialize and Deserialize for any type following the `derive_eq` and `derive_default` examples in the stdlib.

We can't implement this deriver function in Noir's stdlib since we don't define Serialize or Deserialize there either - that will be work for the authors of those libraries. Since it should be possible now, I'm closing this issue.
