### ISSUE TITLE
`nargo codegen-verify` does not produce a full smart contract if backend has been renamed

### ISSUE THREAD

**Issue by Cryptuude** [noir-lang/noir#3477]
### Aim

After upgrading from Noir 0.8.0 to Noir 0.19.2 ,  I tried generating a solidity verifier for my circuit.

### Expected Behavior

A working solidity program with a UltraVerifier contract defined.

### Bug

I successfully ran `nargo compile`. Running `nargo codegen-verifier` also returns `[test] Contract successfully created and located at circuits/test/contract/test/plonk_vk.sol
`; but the resulting contract (attached) is missing the verifier parts. 
[plonk_vk.sol.txt](https://github.com/noir-lang/noir/files/13325453/plonk_vk.sol.txt)

### To Reproduce

1. Install `nargo` via the nix instructions ( or include nargo via a nix flake)
2. Copy the default `acvm-backend-barretenberg` backend into another backend folder, `nargo backend use` that folder (don't know if this causes the bug, but I have to do so because I am using a wrapped backend)
3. `nargo init`
4. `nargo codegen-verifier`

### Installation Method

Compiled from source

### Nargo Version

nargo 0.17.0 (git version hash: 7de37c6935571c2865eca7ce11da0038ff735b2f, is dirty: false)

### Additional Context

I am running NixOS so I had to wrap the backend in script to provide it the libraries required to run. I can imagine this /might/ be a problem if this binary downloads more binaries that it then tries to execute, or has other hidden dependencies. 

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
> Copy the default acvm-backend-barretenberg backend into another backend folder, nargo backend use that folder (don't know if this causes the bug, but I have to do so because I am using a wrapped backend)

Hey @Cryptuude, this step is the issue. The `BaseUltraVerifier` and `UltraVerifier` contracts should _really_ be provided by the backend but `bb` actually only gives us the verification key library. We've then special cased the default backend which is named `acvm-backend-barretenberg` so that nargo injects those contracts itself.

Backends with a different name are assumed to not be `bb` so we don't perform any of the special-casing in that scenario. You should be able to place your patched binary back into the `acvm-backend-barretenberg` directory which will get you a working contract again, the only issue is that you'll automatically download a non-patched version to replace it if we bump the expected `bb` version.  

See here for where we have this special case.
https://github.com/noir-lang/noir/blob/a22898d68712192a6ad014986f11f1f55ca9a2c1/tooling/nargo_cli/src/cli/codegen_verifier_cmd.rs#L89-L92

Ideally `bb` should be updated to return the full contract file but it's competing with other priorities.
