### ISSUE TITLE
Implement Glob Import Feature

### ISSUE THREAD

**Issue by f01dab1e** [noir-lang/noir#3689]
### Problem

Current import system requires individual module or function imports, leading to lengthy and cluttered import sections.

### Happy Case

Enable use module::*; syntax for importing all items from a module, simplifying code and reducing import lines.

```rust
use dep::std::prelude::*;
```

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
I generally find glob imports to make the code unreadable and (I could be misremembering) caused quite a few problems in the codebase of rust-analyzer and rustc, I'm guessing because glob imports have different semantics to normal imports. So for example, the following code should compile:

```
mod foo {
    pub struct Hello;
    pub struct Bye;
}

mod bar {

    use super::foo::*;
    struct Hello {
        a: u8,
    }
    fn baz() {
        let h = Hello;
    }
}
```

Note that we are using a glob import to import Hello from `foo` and then we are declaring a `Hello` in `bar`. Changing to `let h = Hello{ a : 0}` should also compile.

If you change  `use super::foo::*;` to `use super::foo::Hello;` then the code will now not compile because you've imported two items under the Hello namespace

**Comment by f01dab1e** [comment]
@kevaundray 

Perhaps it shouldn't be introduced as a function for users, but rather as an internal feature? This way, instead of manually specifying [https://github.com/noir-lang/noir/pull/3693/files#diff-9ed086179960462bc0c6c2e7dc2594abfbc5f97f4cff55c5421b341cacb1e45aR54] which items need to be imported, we could just import all public items automatically.
