### ISSUE TITLE
Remove `setpub` array

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#370]
To start with, my understanding of `setpub` is quite fuzzy. My understanding is that it was a method to make a value calculated inside the `main` context public before we had return values. At this point it seems entirely redundant barring any edge-cases I'm unaware of.

When return values were added it was mentioned that we would potentially remove `setpub` as a consequence but some groundwork was necessary first.

https://github.com/noir-lang/noir/pull/232#issuecomment-1150326248
> This relates to https://github.com/noir-lang/noir/issues/227, though as stated doesn't enforce pub by default and doesn't remove set_pub (I believe array support with Operation::Constrain Eq is needed for this).

It's not entirely clear to me what `Operation::Constrain Eq` means in this context (A reference to [this](https://github.com/noir-lang/noir/blob/2de7204df1875a3643b7bd36ddd4e59f29b2d92d/crates/noirc_evaluator/src/ssa/code_gen.rs#L88-L97)?). The codebase has had some significant changes since then however and returning an array works fine from my tests.

I have a branch which removes `setpub` array which I can make a PR with but I wanted to check if I'm missing relevant info first.

**Comment by jfecher** [comment]
Your assumptions are correct, and `setpub` is indeed deprecated currently in favor of return values. `Operation::Constrain::Eq` for arrays has since been implemented* so we would gladly accept a PR removing this deprecated feature.

* it used to be separate from the general `Eq` operation in our SSA IR, merging the two together thus implemented the missing functionality
