### ISSUE TITLE
GLIBC required to run Nargo

### ISSUE THREAD

**Issue by spalladino** [noir-lang/noir#4132]
### Aim

Compile an Aztec Contract using Nargo on a fresh environment.

### Expected Behavior

Running `nargo compile` downloads a backend and compiles successfully, without needing additional dependencies to be installed.

### Bug

Nargo fails with `/lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.32' not found`. This happens on an Ubuntu system.

### Installation Method

Binary

### Nargo Version

0.22.0+fe0b9975a28970af915b39f5f338e880577b60f8

### Additional Context

I'd expect either `noirup` to download glibc automatically, or for the bb backend to not depend on dynamically loading glibc, or for the documentation to include it as a requirement.

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
This issue was introduced in [this PR](https://github.com/AztecProtocol/aztec-packages/pull/3036) afaik. I'm going to move this issue onto aztec-packages as it's in reality an issue with the `bb` build system.

Noir can't and shouldn't guarantee that it will provide a working environment for `bb`, instead `bb` should provide an official installation method for prebuilt binaries and test that this works on specified versions of ubuntu, etc.

> I'd expect either noirup to download glibc automatically

We shouldn't try to fix this here as it's two hops away from where the requirement for this dynamic library is being introduced so we'll always be chasing future breaking changes in `bb`. We also don't want to get to the point where we're routinely asking users to reinstall noirup from scratch as that breaks the "just run `noirup` again" debugging step.

**Comment by spalladino** [comment]
Thanks @TomAFrench!
