### ISSUE TITLE
Compiled should introduce an optimalisation and inject helper unconstrained functions to help with division.

### ISSUE THREAD

**Issue by LogvinovLeon** [noir-lang/noir#4214]
### Problem

[This section of docs](https://noir-lang.org/docs/dev/noir/concepts/unconstrained) describes the optimalization that if some computation is cheaper to verify than compute - we should compute it in unconstrained code and only verify the results in constrained.

In general case - this is too high level for an optimiser to pick up.
For integer division - it can be done quite easily and introduce measurable benefits.

### Happy Case

When compiler see integer division - it should replace it with an unconstrained division and constrained multiplication reducing the backend circuit size

### Additional Context

I've recently submitted a PR to noir-trie-proofs that does this optimalisation manually and it saves 3% of gates.
https://github.com/aragonzkresearch/noir-trie-proofs/pull/11

### Would you like to submit a PR for this Issue?

Maybe

### Support Needs

I might be interested in submitting a PR with this change, but I'll need some guidance. Please let me know if you think it's a good idea and where would be the best stage to do a transformation like that.

**Comment by TomAFrench** [comment]
All division is unconstrained division! Whenever we do integer division we calculate the quotient and remainder in an unconstrained function, range constrain these two witnesses, and then enforce that `numerator = quotient * denominator + remainder`.

https://github.com/noir-lang/noir/blob/26e961860709e9c0ab3d1eb561fd39b5bd95a0fb/compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs#L714-L762

A lot of the savings that from that refactor come down to:
- The bug which is being fixed in #4217 (something I noticed due to this issue so thank you!)
- No longer doing bitwise ANDs (these are really unnecessary as it's equivalent to taking the remainder from a division in this case, something we're doing when casting to a `u4` anyway)
- Using the results from a single euclidean division to give both nibbles in a byte rather than doing a euclidean division for each nibble.

The last one is a potential compiler improvement but it would require us to cache a lot of division results and the situations where it would come up most (splitting an integer into limbs of smaller integers) are easy enough to recognise that I think that adding a `fn split_byte(byte: u8) -> (u4, u4)` with an unconstrained helper would handle most cases.
