### ISSUE TITLE
LSP to set nargo path based on nargo or aztec-nargo

### ISSUE THREAD

**Issue by rahul-kothari** [noir-lang/noir#4233]
### Problem

Currently aztec.nr devs need to manually set the VS Code path to point to aztec-nargo. Ideally this is automated.
make it part of Nargo.toml config, where plugin could look at `type=contract` or `type=bin` to decide if they are using aztec-nargo which resides at `/Users/rahulkothari/.aztec/bin/aztec-nargo` or nargo which is automatically found. 

### Happy Case

No manual config necessary.
Remember that some coders use both nargo and aztec-nargo

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
Just to make sure I'm on the same page with the problem:
1. Is the Issue here that the Noir Language Support VS Code extension picks up:
  i. `nargo` at its vanilla default location
  ii. But not `aztec-nargo` at its own different default location?
3. Which leads to:
  i. Aztec devs without `nargo` doesn't get LSP features in VS Code
  ii. Aztec devs with `nargo` (but at a different version versus `aztec-nargo`) gets "incorrect" LSP features in VS Code?

Assuming the understanding above is correct, there are two possible solutions off the top of my hat:
1. **Modify the VS Code extension to also pick up `aztec-nargo` at its custom default location**
  i. As originally suggested in this Issue
  ii. Quite opinionated imo
  iii. Should transfer this Issue to the [vscode-noir] repo if we're going this path
2. **Modify `aztec-nargo` to symlink as `nargo` at the vanilla default location**
  i. I would prefer this (but am not aware if this carries any potential contract development problems)

Great to hear your further thoughts @rahul-kothari.

**Comment by TomAFrench** [comment]
Closed in https://github.com/noir-lang/vscode-noir/pull/67
