### ISSUE TITLE
`arraysum` Not Found

### ISSUE THREAD

**Issue by Globallager** [noir-lang/noir#532]
# Description

## Aim

Sum elements of an array using `std::array::sum(_input)`.

## Expected behavior

Successfully proving a Noir program as follows:

```rust
use dep::std;

fn main() {
    let arr = [1, 2];
    let arr_sum = std::array::sum(arr);
    constrain arr_sum == 3;
}
```

## Bug

Running `nargo prove p` on the above fails with:

```sh
thread 'main' panicked at 'internal error: entered unreachable code: cannot find a low level opcode with the name arraysum in the IR', crates/noirc_evaluator/src/ssa/code_gen.rs:613:17
```

# Environment

- OS: macOS
- Proving backend
  - [ ] default
  - [x] wasm-base
    - `aztec_backend = { optional = true, package = "barretenberg_wasm", git = "https://github.com/noir-lang/aztec_backend", rev = "fb42a54a04f3952f422e8fa4eff4f8eb2ca4e51b" }`

# Additional context

Not sure if it's simply unimplemented or a bug. Feel free to re-label as appropriate.

**Comment by guipublic** [comment]
arraysum and arrayprod are deprecated functions, they can easily be implemented by the user, for instance arraysum is:
```
fn sum(a:[Field]) -> Field {
  let mut s = 0;
  for i in a {
    s = s + i;
  };
  s
}
```

Like in rust, we want to keep the stdlib lean so that we minimize backward compatibility issues. You can refer to https://users.rust-lang.org/t/rust-should-have-a-big-standard-library-and-heres-why/37449/25 for discussion about what should be in stdlib.
As a result, we are going to remove completely arraysum and arrayprod.

**Comment by saeed1214** [comment]
great
