### ISSUE TITLE
NoirJS doesn't report return values when doing witness gen on a function with databus (return_data) 

### ISSUE THREAD

**Issue by sirasistant** [noir-lang/noir#5715]
### Aim

Get the return values along with the witness when calling a function with return_data, to pass them to the next circuit in the IVC chain.

### Expected Behavior

As the prover entity, I should be able to get the databus return_data to pass it to the next circuit for recursive verification.

### Bug

They are not due to this line https://github.com/noir-lang/noir/blob/master/tooling/noirc_abi/src/lib.rs#L351

### To Reproduce

1. Create a noir circuit with return_data
2. Call it via noirjs

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
> They are not due to this line https://github.com/noir-lang/noir/blob/master/tooling/noirc_abi/src/lib.rs#L351

This isn't the root cause of this issue. The issue is that the databus return data is held in a memory block rather than the witness map (note that we still reserve witness indices for databus return values, they're just not used).

In order to solve this we'll have to make changes to the ACVM as it assumes that the full state which the user is interested in will be contained in the witness map.

**Comment by TomAFrench** [comment]
I've spoken with @guipublic on this and the current thinking is that we can ensure there's a set of witness indices which correspond to the contents of the databus return array (but these witnesses aren't made public). We can include these witnesses in the ABI similarly to standard return values (but distinguished by the return visibility) and so ABI decoding will "just work".

This may result in slightly less good ACIR gen in some cases but it would be basically equivalent to non-databus programs (except without the cost of public inputs).
