### ISSUE TITLE
Tracking Issue : Rework the way arrays are done in SSA

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#582]
# Problem

Guillaume noted that we can remove the optimisation that does not copy arrays from functions called.   

# Solution

Consider re-doing the way arrays are implemented
 
# Alternatives considered

(Describe any alternative solutions you have considered.)

# Additional context

(If applicable.)

**Comment by jfecher** [comment]
> Guillaume noted that we can remove the optimisation that does not copy arrays from functions called.

Reworking arrays should be more pervasive than this. It should be more of an internal refactoring to track arrays through NodeIds like other values instead of through ObjectTypes. Tracking through ObjectTypes does not make much sense as these are converted from the frontend's Type which does not track specific arrays either so this information is not present initially and must be filled in with placeholders until it is fixed later.
When doing this refactoring we should also keep in mind that we want to add additional functionality for arrays/vectors/slices (#374) in the future.
