### ISSUE TITLE
`FunctionDefinition.has_named_attribute(quote {test})` returns false for test functions

### ISSUE THREAD

**Issue by Thunkar** [noir-lang/noir#6009]
### Aim

I want to be able to filter out test functions when iterating through a module.

### Expected Behavior

`FunctionDefinition.has_named_attribute(quote {test})` returns true for `#[test]` functions, or an extra `.is_test()` helper is added.

### Bug

`FunctionDefinition.has_named_attribute(quote {test})` for a test function returns false.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by asterite** [comment]
So, the idea of `has_named_attribute` is that it only checks against custom attributes. I wonder whether we should add an `is_test()` as you suggested... or maybe we can have `has_named_attribute` also check the built-in attributes (I think I'll do this).

I also wonder if `has_named_attribute` should take a `str<N>` instead of `Quoted`, what do you think?

**Comment by asterite** [comment]
> I'd be fine if the string just matched against the name but we should 100% avoid it matching against arguments as well. It works for a single word but we don't want to worry about spacing being different in the annotation or anything like that.

What if we lexed both the argument and the attribute and check that the tokens match? That way spacing being different wouldn't be an issue.

I'm still not sure about it, though. I'm just wondering what's the best way to check if something is annotated with `#[aztec(public)]` if we don't want to change that to `#[aztec_public]`.
