### ISSUE TITLE
is it possible to have two programs that are different from the prover perspective but generate the same set of constraints?

### ISSUE THREAD

**Issue by lucadonnoh** [noir-lang/noir#604]
this question is inspired by [this thread](https://twitter.com/smpalladino/status/1607483523866451968?s=46&t=4jNYZHUo1RZ0URFdAVTV2g) and [this article](https://blog.trailofbits.com/2022/09/15/it-pays-to-be-circomspect/) about the risk of using `<--` in circom instead of `<==`. is it possible to have a similar scenario in noir? if yes it would be very useful to have an example of it, if not an explanation why

**Comment by lucadonnoh** [comment]
other than Circom, another example is Cairo non-deterministic programming using hints which are only executed by the prover and not seen by the verifier, and two programs with different hints (so different from the prover perspective) can generate the same proof

**Comment by kevaundray** [comment]
Currently in Noir, this non-determinism is not given directly to the user because as you noted, it can be dangerous if the correct constraints aren't applied. 

The compiler is allowed to do this, but in very specific scenarios and it can only be for specific defined operations.

There are ideas for introducing a more generic concept safely, however there is no particular rush as we want to think carefully about how it gets introduced and the scenarios in which one may use this

**Comment by lucadonnoh** [comment]
i didn’t intend this as a feature, i just wanted to be aware if there was any similar risk in noir. thank you for the clarification!
