### ISSUE TITLE
Disallow return values from being constants

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#655]
# Problem

The current program:

```rust
fn main(x : Field) -> [Field;2] {
  [x, 2]
}
```

Will allow the user to return a constant as a public output.

# Solution

Users will need to differentiate between a program constant and a public output(which is public and will vary).

ie you cannot return a constant as a public output.

# Alternatives considered

# Additional context

This is a tracking issue to collect feedback

**Comment by jfecher** [comment]
Can you elaborate on the context for this issue? We have discussed it a bit in private but without the context given here it sounds like an arbitrary restriction to place.

**Comment by guipublic** [comment]
IHMO, returning [x,2] is NOT a problem per se.

The way we handle this case is by creating a witness which is constrained to the hardcoded value (2 in the example).
This is fine because it corresponds to what the user wrote and it is safe.
We could however issue a warning explaining that this value does not need to be returned because it is always 2.

**Comment by kevaundray** [comment]
@guipublic I have assigned this to you -- you can choose to issue a warning or disallow. I don't think it matters that much right now
