### ISSUE TITLE
Move ACIR optimisation pass out of Evaluator module

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#658]
This is a tracking issue for a TODO from the PR #647 and is also made to gather opinions.

The idea being that the Evaluator simply produces the ACIR, then the Driver or nargo calls `acvm::compile` to optimise the ACIR, instead of doing the optimisation inside of the Evaluator.

This allows us to separate the optimisation being done by ACVM from the Evaluator which is producing ACVM.

**Comment by guipublic** [comment]
> This allows us to separate the optimisation being done by ACVM from the Evaluator which is producing ACVM.

Why do you want to do this?
Note that the code is already separated as acvm and the evaluator live in different repositories

**Comment by TomAFrench** [comment]
> Why do you want to do this?

This is wanted so that we can generate backend-agnostic build artifacts which can be tailored to a particular backend rather than having to compile again from source. We need to return unoptimised ACIR to nargo in order to do this.

I took a quick look at separating this out. This is quite simple for the evaluator however we also bake in knowledge about the backend in the frontend when dealing with [foreign functions](https://github.com/noir-lang/noir/blob/a69758c0dff98bb23539df9c13366ef5b23e6b0f/crates/noirc_frontend/src/node_interner.rs#L588)


Related https://github.com/noir-lang/acvm/issues/43

**Comment by kevaundray** [comment]
@TomAFrench what is the status of this?

**Comment by TomAFrench** [comment]
This is addressed now as the optimiser is called by `nargo` rather than the noir compiler.
