### ISSUE TITLE
`private-kernel-lib` tests are failing on Noir master

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#6665]
See CI run which runs `nargo test` on the protocol circuit tests: https://github.com/noir-lang/noir/actions/runs/12091844455/job/33720813101?pr=6660

These are all tests which don't make use of custom foreign calls so they should be relatively simple to pull out into this repository, minimise and create a regression test.

**Comment by asterite** [comment]
Debugging this a bit, it seems the issue is with instruction hoisting in constant folding. There's code like this:

```noir
        if num_note_hashes != 0 {
            let x = num_note_hashes - 1;
```

and we get `attempt to subtract with overflow` likely because that subtraction is done even if `num_note_hashes` is zero. I still need to figure out exactly what's the issue, but disabling that hoisting fixes it.

**Comment by TomAFrench** [comment]
Answered in #6672 but yeah we should disable this optimization on any instructions which break it so that we can get tests passing (as it's a relatively recent optimization this won't cause a deal-breaking regression). We can then look at how to optimize more of these instructions in followups.
