### ISSUE TITLE
`private_kernel_tail_to_public::tests::enqueued_public_calls_with_teardown_gas` fails in master

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#6674]
This test is currently showing as failing in our external repo checks: https://github.com/noir-lang/noir/actions/runs/12123521659/job/33799364171?pr=6672#step:6:50

We should pull a reproduction case into this repo and fix it.

**Comment by asterite** [comment]
So far what I found is that reverting https://github.com/noir-lang/noir/pull/6088 makes the test pass.

I also found that this SSA:

```
v258 = load v252 -> [Field; 3]
inc_rc v258
v265 = load v252 -> [Field; 3]
inc_rc v265
```

becomes this with that optimization above:

```
v258 = load v252 -> [Field; 3]
inc_rc v258
inc_rc v265
```

That's because we can't find a `store` between the two loads to the same address, so they are unified. But this means we end up with two `inc_rc` for the same array, where previously we only had one. I don't know if that could lead to incorrectness or just to a performance regression (there was one in that PR, maybe it's related?)

**Comment by jfecher** [comment]
> But this means we end up with two inc_rc for the same array, where previously we only had one.

They're both loaded from the same address with no stores in between so it should be the same array loaded each time. So the first example should be equivalent to the second - not sure why this would cause issues.
