### ISSUE TITLE
Rename SsaContext to SSAContext

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#755]

**Comment by 0xYYY** [comment]
Hi, I'm looking for some good-first-issues to contribute in this repo, and would be happy to take this one.

However, before getting to it, i would like to check if this change conforms to the Rust naming convention. 

In [Rust's API guideline](https://rust-lang.github.io/api-guidelines/naming.html), it states that "*In UpperCamelCase, acronyms and contractions of compound words count as one word: use Uuid rather than UUID, ...*", as can see with the naming of [`std::net::TcpStream`](https://doc.rust-lang.org/std/net/struct.TcpStream.html).

So should we still go for this change? wdyt

**Comment by kevaundray** [comment]
Hey, thanks for choosing to contribute to the Noir.

You are correct, we have not followed this standard throughout the codebase though. If you want, you can change the structs to follow the guideline. Another one which we can phase out, is the usage of `get_foo` instead of `foo`

**Comment by jfecher** [comment]
I think we should keep `SsaContext` and change any other types throughout the codebase that do not follow this pattern

**Comment by 0xYYY** [comment]
Thanks for the inputs. Then I think I'll try to identify namings of the mentioned cases:
1. those not following UpperCamelCase (or any other) guideline,
2. usage of `get_foo` instead of `foo`.

And track them in a separate issue, then send out a PR for it.

**Comment by kevaundray** [comment]
Closing this issue as we won't be doing this.
