### ISSUE TITLE
Support Multidimensional / Nested Arrays

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#828]
# Problem

Currently arrays can only be initiated in 1D, which could be less convenient for certain development works.

# Solution

Add support / syntax sugar for >1D arrays, for example:

```rust
fn main() {
    let mut grid = [[0; 3]; 3];
    grid[1][1] = 1;
    grid[2][2] = 2;
    constrain grid [0][0] == 0;
    constrain grid [1][1] == 1;
    constrain grid [2][2] == 2;
}
```

# Alternatives considered

The same capability can be mimicked with a large 1D array (e.g. instead of creating a 3 * 3 array, create a 9-element array).

This approach however results in less intuitive and readable, hence maintainable code, especially for complex projects.

**Comment by jfecher** [comment]
After starting this, I was taking the approach of desugaring `foo: [[T; N]; M]` into `foo: [T; N * M]` but noticed that the desugaring will not be so simple as we will need to support `let first_row = foo[0];` which traditionally involves a copy of the whole array since it assigns an array into another variable. Here however, `foo[0]` would just be a slice of `foo` which has only 1 dimension internally. To support it then, we'd need to support copying and general handling of slices of arrays as well.

It may be easier to support true multidimensional arrays then.
