### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by zakrad** [noir-lang/noir#981]
### Aim

I was following the Noir hello_world tutorial and encountered this error after `nargo check` 

### Expected behavior

It should generate two additional files in my hello_world folder

### Bug

```
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
```

### To reproduce

1.
2.
3.
4.

### Installation method

Compiled from source

### Nargo version

nargo 0.3.0

**Comment by aguzmant103** [comment]
Faced this too just now

**Comment by aguzmant103** [comment]
If it helps, I installed Noir with WASM backend https://noir-lang.org/getting_started/nargo/installation.html#option-21-install-executable-with-wasm-backend

**Comment by zakrad** [comment]
Yeah I also installed Noir with WASM backend

**Comment by TomAFrench** [comment]
Hi @aguzmant103 and @zakrad , thank you for this report. I'm unable to reproduce this on the prebuilt binaries or on the tip of master.

Can you confirm which commit you're building from and share the full error message so that I can see where this error is being thrown?

**Comment by TomAFrench** [comment]
Yes, that helps a lot. Thank you.

Looks like the embedded std lib isn't being found somehow. It works fine on Ubuntu so potentially it's a windows specific issue? Something related to forward vs backwards slashes not being handled in the prefix for `StdLibAssets`? 

@kobyhallx, I think you have a windows installation. Could you test this out to see if you can reproduce?

**Comment by zakrad** [comment]
I dont know which commit but I pulled with this `git clone git@github.com:noir-lang/noir.git` yesterday

**Comment by zakrad** [comment]
> Yes, that helps a lot. Thank you.
> 
> Looks like the embedded std lib isn't being found somehow. It works fine on Ubuntu so potentially it's a windows specific issue? Something related to forward vs backwards slashes not being handled in the prefix for `StdLibAssets`?
> 
> @kobyhallx, I think you have a windows installation. Could you test this out to see if you can reproduce?

I also tried with wsl on windows with same error

**Comment by aguzmant103** [comment]
I'm on Windows directly so that theory could be right

**Comment by TomAFrench** [comment]
This definitely seems to be a windows specific error which snuck through due to our test suite not properly alerting failing tests on windows.

Tentative fix here: #990. If you could try building from commit [999b49a](https://github.com/noir-lang/noir/pull/990/commits/999b49a624d2d1390bbf7162d70fbac2365806b0) and seeing if you still get this error I'd be very grateful.

**Comment by aguzmant103** [comment]
@TomAFrench still there unfortunately
![image](https://user-images.githubusercontent.com/67167307/225495710-8f0e7a5d-d1f3-4299-ab06-67c010f76c13.png)

Is it okay I just installed it on top of the last one? (I couldn't find how to remove the old version). I just:
1. git cloned to the branch with the fix
2. followed the same WASM installation procedure

**Comment by TomAFrench** [comment]
Yeah, that's perfect. Thanks for testing.

Not entirely surprising that it didn't work. My guess is the fake "path" for the stdlib is getting converted from `std/lib.nr` to `std\lib.nr` on windows which results in it not matching the pattern we check for in order to return the stdlib but this would have been a change fix than we'll have to do for this.

**Comment by aguzmant103** [comment]
@TomAFrench this issue was closed by mistake? Lmk what other things to try :)
